loknowbot/instructions/urls.py
from django.urls import path

from loknowbot.instructions import views

app_name = 'instructions'

urlpatterns = [
    path('<int:pk>/', views.InstructionDetailView.as_view(), name='instruction-set-detail'),
    path('add/', views.InstructionCreateView.as_view(), name='instruction-set-create'),
    path('list/', views.InstructionListView.as_view(), name='instruction-set-list'),
    path('update/<int:pk>/', views.InstructionUpdateView.as_view(), name='instruction-set-update'),
]

loknowbot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from loknowbot import views
from loknowbot.instructions import urls as instructions_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instructions/', include(instructions_urls)),
    path('', views.IndexView.as_view(), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

loknowbot/instructions/models.py
from math import sqrt

from django.urls import reverse
from django.db import models
from django.utils.translation import gettext as _


class InstructionSet(models.Model):
    up = models.IntegerField(_('Number of steps in the UP direction'), default=0)
    down = models.IntegerField(_('Number of steps in the DOWN direction'), default=0)
    left = models.IntegerField(_('Number of steps in the LEFT direction'), default=0)
    right = models.IntegerField(_('Number of steps in the RIGHT direction'), default=0)

    class Meta:
        verbose_name = _('Instruction Set')
        verbose_name_plural = _('Instruction Sets')
        ordering = ['id']

    def __str__(self):
        return f'Instruction Set #{self.id}'

    def get_absolute_url(self):
        return reverse('instructions:instruction-set-detail', args=[str(self.id)])

    def get_euclidean_dist(self):
        x_dir = self.left - self.right
        y_dir = self.up - self.down
        return round(sqrt(x_dir**2 + y_dir**2), 1)

    def get_num_of_instructions(self):
        # Movement in any direction is considered 1 instruction
        num_instructions = 0
        if self.up != 0:
            num_instructions += 1
        if self.down != 0:
            num_instructions += 1
        if self.left != 0:
            num_instructions += 1
        if self.right != 0:
            num_instructions += 1
        return num_instructions

loknowbot/instructions/forms.py
from django import forms

from .models import InstructionSet


class InstructionForm(forms.ModelForm):
    up = forms.IntegerField(min_value=0,
                            widget=forms.NumberInput(attrs={"class": "form-control"}),
                            help_text='Enter an integer for going UP')
    down = forms.IntegerField(min_value=0,
                              widget=forms.NumberInput(attrs={"class": "form-control"}),
                              help_text='Enter an integer for going DOWN')
    left = forms.IntegerField(min_value=0, widget=forms.NumberInput(attrs={"class": "form-control"}),
                              help_text='Enter an integer for going LEFT')
    right = forms.IntegerField(min_value=0, widget=forms.NumberInput(attrs={"class": "form-control"}),
                               help_text='Enter an integer for going RIGHT')


    class Meta:
        model = InstructionSet
        fields = ('up', 'down', 'left', 'right')

loknowbot/instructions/views.py
from django.views.generic import DetailView, ListView, CreateView, UpdateView
from django.urls import reverse

from .models import InstructionSet
from .forms import InstructionForm


class InstructionDetailView(DetailView):
    template_name = 'instruction_set_detail.html'
    model = InstructionSet
    context_object_name = 'instruction_set'
    slug_field = 'id'

class InstructionListView(ListView):
    template_name = 'instruction_set_list.html'
    context_object_name = 'instruction_sets'
    model = InstructionSet

class InstructionCreateView(CreateView):
    template_name = 'instruction_set_create.html'
    model = InstructionSet
    form_class = InstructionForm

    def get_success_url(self):
        return reverse('instructions:instruction-set-detail', kwargs={'pk': self.object.id})

class InstructionUpdateView(UpdateView):
    template_name = 'instruction_set_update.html'
    model = InstructionSet
    form_class = InstructionForm

    def get_success_url(self):
        return reverse('instructions:instruction-set-detail', kwargs={'pk': self.object.id})

loknowbot/views.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

loknowbot/instructions/templates/instruction_set_create.html
{% extends "base.html" %}

{% block content %}

    <div class="card-block">
        <div class="row">
            <div class="col-md-6">
                <h5 class="mt-5">Instruction set</h5>
                <hr>
                <form action="{% url 'instructions:instruction-set-create' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success shadow-2 mb-4" title="Save instructions" data-toggle="tooltip">Save instructions</button>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

loknowbot/instructions/templates/instruction_set_detail.html
{% extends "base.html" %}

{% block content %}

    <form action="{% url 'instructions:instruction-set-update' instruction_set.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Details of Instruction set of {{ instruction_set.id }}</h2>
        <div class="card-body">
            <ul>
                <li>Steps in UP direction {{ instruction_set.up }}</li>
                <li>Steps in DOWN direction {{ instruction_set.down }}</li>
                <li>Steps in LEFT direction {{ instruction_set.left }}</li>
                <li>Steps in RIGHT direction {{ instruction_set.right }}</li>
                <li><h6>Distance travelled (euclidean): {{ instruction_set.get_euclidean_dist }} </h6></li>
                <li><h6>Number of instructions: {{ instruction_set.get_num_of_instructions }} </h6></li>
            </ul>
            <button class="btn btn-primary" type="submit">Edit</button>
        </div>
    </form>
    <div>
        <a href="{% url 'instructions:instruction-set-list' %}">
            <button class="btn btn-secondary">Back to list</button>
        </a>
    </div>


{% endblock %}

loknowbot/instructions/templates/instruction_set_list.html
{% extends "base.html" %}

{% block content %}

    <h2>List of instruction sets</h2>

    {% for set in instruction_sets %}
        <div class="card">
            <h5><a href="{{ set.get_absolute_url }}">{{set}}</a></h5>
            <ul>
                <li>Steps in UP direction {{ set.up }}</li>
                <li>Steps in DOWN direction {{ set.down }}</li>
                <li>Steps in LEFT direction {{ set.left }}</li>
                <li>Steps in RIGHT direction {{ set.right }}</li>
                <li><h6>Distance travelled (euclidean): {{ set.get_euclidean_dist }} </h6></li>
                <li><h6>Number of instructions: {{ set.get_num_of_instructions }} </h6></li>
            </ul>
        </div>
    {% endfor %}

{% endblock %}

loknowbot/instructions/templates/instruction_set_update.html
{% extends "base.html" %}

{% block content %}

    <div class="card-block">
        <div class="row">
            <div class="col-md-6">
                <h5 class="mt-5">Instruction set</h5>
                <hr>
                 <form action="{% url 'instructions:instruction-set-update' object.id%}" method="POST" enctype="multipart/form-data">
                     {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success shadow-2 mb-4" title="Save instructions" data-toggle="tooltip">Save instructions</button>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

loknowbot/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Super Awesome Bot</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</body>
</html>

loknowbot/templates/index.html
{% extends "base.html" %}

{% include 'navbar.html' %}

{% block content %}

    <h1>My Super Awesome Bot</h1>

    <p>Use navbar links to view existing instruction sets or create your own =)</p>

{% endblock %}

loknowbot/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'instructions:instruction-set-list' %}">List of Instruction Sets</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'instructions:instruction-set-create' %}">Create Instruction Set</a>
            </li>
        </ul>
    </div>
</nav>